//! Vyrox Proxy — Containment Action Executor
//!
//! Single-purpose HTTP service that executes EDR containment actions
//! (host isolation, process kill, network quarantine) on behalf of the
//! Vyrox SOC platform. Every action requires a human-approved request
//! signed with the shared HMAC secret; the proxy verifies the signature
//! and serves as the only code path that calls the EDR API.
//!
//! ## Request lifecycle
//!
//! For every `POST /execute` call:
//!
//! 1. **Capture raw body** before any parsing. The HMAC must be verified
//!    against the bytes the client signed, not against a re-serialized
//!    version of the parsed JSON (which would re-order keys and change
//!    the digest).
//! 2. **Verify HMAC** in constant time (see `hmac::verify_signature`).
//! 3. **Parse the JSON body** into an `ExecuteRequest`.
//! 4. **Replay window check** — reject if `approved_at` is outside the
//!    30-second window in either direction.
//! 5. **Nonce dedup** — claim the `request_id` in the nonce store. If
//!    already completed, return the cached response. If still in flight,
//!    return 409 Conflict.
//! 6. **Audit before action** — write an audit entry recording the
//!    intent BEFORE invoking the EDR (`audit::append_audit`). This way
//!    a crash mid-action still leaves a forensic trail.
//! 7. **Execute via the EDR client** (or return early if DRY_RUN).
//! 8. **Cache the response** in the nonce store so retries are idempotent.
//!
//! ## Endpoints
//!
//! | Method | Path             | Purpose                              |
//! |--------|------------------|--------------------------------------|
//! | GET    | /health          | Liveness probe                       |
//! | POST   | /execute         | Execute a containment action         |
//! | GET    | /audit/export    | Tenant-scoped audit log export       |

use std::env;
use std::time::{SystemTime, UNIX_EPOCH};

use axum::body::Bytes;
use axum::extract::{Query, State};
use axum::http::{HeaderMap, StatusCode};
use axum::response::Json;
use axum::routing::{get, post};
use axum::Router;
use serde::{Deserialize, Serialize};
use serde_json::json;
use tracing::{info, warn};

mod actions;
mod audit;
mod edr;
mod hmac;
mod nonce;

/// Replay protection window. Requests with `approved_at` more than this
/// many seconds away from the current time (in either direction) are
/// rejected. The bound is symmetric so we also reject far-future
/// timestamps caused by client clock skew or deliberate manipulation.
const REPLAY_WINDOW_SECONDS: i64 = 30;

/// Application state. Cloned into every request handler, so anything
/// inside must be cheap to clone (Arc-wrapped data, primitives, etc.).
#[derive(Clone)]
struct AppState {
    /// Shared HMAC-SHA256 secret. Provided via env var; never logged.
    hmac_secret: String,

    /// Path to the append-only JSONL audit log.
    audit_log_path: String,

    /// If true, action execution is skipped and the EDR is never called.
    /// Default for development and CI. Production must set DRY_RUN=false
    /// **explicitly** (see `main` — we err on the side of safe-by-default).
    dry_run: bool,

    /// In-process dedup store keyed by `request_id`. See `nonce.rs`.
    nonces: nonce::NonceStore,

    /// EDR client implementation. Currently dispatches to the configured
    /// EDR (CrowdStrike Falcon for v0.1-alpha pilot). See `edr.rs`.
    edr: edr::EdrClient,

    /// SHA-256 hash chain state for the audit log. Seeded at boot from
    /// the last entry on disk so restarts do not break the chain.
    /// See `audit::ChainState`.
    audit_chain: audit::ChainState,
}

/// Request payload for `POST /execute`.
///
/// **Stability:** This struct is part of the wire contract with the
/// Vyrox Discord bot. Changes here must be coordinated with the Python
/// side (`vyrox/discord_bot/proxy_client.py`).
#[derive(Debug, Deserialize, Serialize)]
struct ExecuteRequest {
    /// Idempotency key. UUID-v4 generated by the Discord bot at the
    /// moment of approval. The proxy uses it to dedupe retries — see
    /// `nonce::NonceStore`. MUST be non-empty.
    request_id: String,

    /// Tenant identifier for multi-tenancy isolation. Tagged on every
    /// audit entry; used to scope `/audit/export`.
    tenant_id: String,

    /// Reference to the original alert that triggered this action.
    /// Carried through to the audit entry for incident correlation.
    alert_id: String,

    /// Type of containment action to execute.
    action_type: actions::ActionType,

    /// Target hostname, device ID, or IP for the action. Format depends
    /// on the EDR — CrowdStrike Falcon uses device IDs (AIDs); a future
    /// SentinelOne integration uses agent UUIDs.
    host: String,

    /// Discord username (or display name) who approved the action.
    /// Recorded in the audit log for accountability.
    approved_by: String,

    /// Unix timestamp (seconds, UTC) of approval. Used for replay
    /// protection in `check_replay_window`. The bot sets this via
    /// `int(time.time())` at button-press time.
    #[serde(rename = "approved_at")]
    approved_at: i64,
}

/// Response payload for `POST /execute`.
#[derive(Debug, Serialize, Deserialize, Clone)]
struct ExecuteResponse {
    /// Human-readable status. One of:
    ///   - "executed" — EDR returned success.
    ///   - "dry_run" — DRY_RUN was set; EDR was not called.
    ///   - "replayed" — request was previously executed; cached result returned.
    status: String,

    /// Whether DRY_RUN was active when this response was generated.
    dry_run: bool,
}

/// Query parameters for the audit export endpoint.
#[derive(Debug, Deserialize)]
struct ExportQuery {
    /// Tenant ID filter. Only audit entries with a matching tenant_id
    /// are returned, ensuring tenant data isolation.
    tenant_id: String,
}

/// Reject if `approved_at` is outside the symmetric replay window.
///
/// The window is symmetric (past *and* future) so that a client whose
/// clock is wildly ahead of ours cannot pre-sign requests for later use.
fn check_replay_window(approved_at: i64) -> Result<(), StatusCode> {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|_| StatusCode::BAD_REQUEST)?
        .as_secs() as i64;

    if (now - approved_at).abs() > REPLAY_WINDOW_SECONDS {
        return Err(StatusCode::GONE);
    }
    Ok(())
}

/// `GET /health`
///
/// Liveness probe for orchestrators (Kubernetes, Fly.io, etc.). The body
/// is intentionally trivial — readiness vs liveness distinctions are not
/// useful for a single-binary stateless service of this size.
async fn health() -> Json<serde_json::Value> {
    Json(json!({"status": "ok"}))
}

/// `POST /execute` — the security-critical entry point.
///
/// See module-level docs for the full request lifecycle. The handler is
/// deliberately verbose and step-numbered to mirror the ordering the
/// security review depends on; do not reorder steps without re-reading
/// the threat model.
async fn execute(
    State(state): State<AppState>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<Json<ExecuteResponse>, StatusCode> {
    // ─ Step 1: Verify HMAC on the RAW bytes we received. ──────────────
    //
    // Critical correctness point: we verify against `body` (the exact
    // bytes from the wire), NOT against a re-serialized version of a
    // parsed struct. The latter would re-order JSON keys and break
    // signatures, and historically did — that bug masked the real
    // verification because differing serialization made every signature
    // mismatch indistinguishable from an invalid signature.
    let signature = headers
        .get("X-Vyrox-Signature")
        .and_then(|v| v.to_str().ok())
        .ok_or(StatusCode::UNAUTHORIZED)?;

    if let Err(err) = hmac::verify_signature(state.hmac_secret.as_bytes(), &body, signature) {
        warn!(error = %err, "signature verification failed");
        return Err(StatusCode::UNAUTHORIZED);
    }

    // ─ Step 2: Parse JSON. ────────────────────────────────────────────
    //
    // Only after the HMAC passes do we trust the body enough to parse
    // it. Parsing before verification would expose any serde panic /
    // pathological input to unauthenticated callers.
    let payload: ExecuteRequest =
        serde_json::from_slice(&body).map_err(|_| StatusCode::BAD_REQUEST)?;

    if payload.request_id.trim().is_empty() {
        return Err(StatusCode::BAD_REQUEST);
    }

    // ─ Step 3: Replay window. ─────────────────────────────────────────
    check_replay_window(payload.approved_at)?;

    // ─ Step 4: Nonce dedup. ───────────────────────────────────────────
    //
    // Claim the request_id. If we've already finished this request,
    // return the cached response — the client gets a byte-identical
    // result and the EDR is NOT called again.
    match state.nonces.claim_or_replay(&payload.request_id) {
        nonce::Outcome::FreshClaim => { /* fall through to execution */ }
        nonce::Outcome::AlreadyExecuted {
            cached_response_json,
        } => {
            info!(request_id = %payload.request_id, "replaying cached response");
            let cached: ExecuteResponse = serde_json::from_str(&cached_response_json)
                .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
            return Ok(Json(ExecuteResponse {
                status: "replayed".to_string(),
                dry_run: cached.dry_run,
            }));
        }
        nonce::Outcome::InFlight => {
            warn!(request_id = %payload.request_id, "duplicate while in-flight");
            return Err(StatusCode::CONFLICT);
        }
    }

    // ─ Step 5: Audit BEFORE acting. ───────────────────────────────────
    //
    // Even if the EDR call panics, crashes the process, or hangs, we
    // have a durable record of the intent on disk. The audit log is the
    // ground truth, not the EDR's response.
    let entry = audit::build_entry(
        payload.tenant_id.clone(),
        format!("{:?}", payload.action_type),
        payload.host.clone(),
        payload.approved_by.clone(),
        state.dry_run,
    );
    if let Err(err) = audit::append_audit(&state.audit_log_path, &state.audit_chain, entry).await {
        // Audit log failure is fatal — we don't proceed without a
        // forensic trail. Release the nonce so the bot can retry once
        // the underlying issue (disk full, perm error) is fixed.
        warn!(error = %err, "audit write failed; releasing nonce claim");
        state.nonces.release_claim(&payload.request_id);
        return Err(StatusCode::INTERNAL_SERVER_ERROR);
    }

    // ─ Step 6: Execute (or skip in DRY_RUN). ──────────────────────────
    let response = if state.dry_run {
        info!(
            request_id = %payload.request_id,
            tenant_id = %payload.tenant_id,
            action = ?payload.action_type,
            host = %payload.host,
            "DRY_RUN: skipping EDR call"
        );
        ExecuteResponse {
            status: "dry_run".to_string(),
            dry_run: true,
        }
    } else {
        // Real execution. The EDR client is responsible for its own
        // retries, timeouts, and error mapping. We treat any error as
        // a 502 Bad Gateway and release the nonce so a retry can try
        // again on fresh state.
        match state.edr.dispatch(payload.action_type, &payload.host).await {
            Ok(()) => ExecuteResponse {
                status: "executed".to_string(),
                dry_run: false,
            },
            Err(err) => {
                warn!(
                    request_id = %payload.request_id,
                    error = %err,
                    "EDR dispatch failed; releasing nonce claim"
                );
                state.nonces.release_claim(&payload.request_id);
                return Err(StatusCode::BAD_GATEWAY);
            }
        }
    };

    // ─ Step 7: Cache the response for future retries. ────────────────
    //
    // Serialize once so subsequent replays return byte-identical output.
    let cache_payload =
        serde_json::to_string(&response).map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
    state
        .nonces
        .record_response(&payload.request_id, cache_payload);

    Ok(Json(response))
}

/// `GET /audit/export?tenant_id=<id>`
///
/// Returns all audit entries for the requested tenant. Filtering happens
/// server-side so a misbehaving caller cannot read another tenant's
/// entries by post-processing.
///
/// ## Authentication
///
/// The export endpoint is HMAC-protected. Callers must send:
///
///   `X-Vyrox-Signature: sha256=<hex>` — HMAC-SHA256 of the canonical
///                                       message `"<tenant_id>:<ts>"`.
///   `X-Vyrox-Timestamp: <unix_seconds>` — UTC unix timestamp used in
///                                         the canonical message.
///
/// The signature is computed over `format!("{tenant_id}:{timestamp}")`
/// using the same `VYROX_HMAC_SECRET` that protects `/execute`. The
/// timestamp is rejected if it falls outside the replay window. This
/// gives `/audit/export` parity with `/execute` for auth + replay
/// protection without needing a request body.
///
/// Without this check, anyone who reaches the proxy can dump any
/// tenant's containment history just by passing a tenant_id query
/// parameter. That was the SEV-2 leak we shipped in the original
/// pilot build; this commit closes it.
///
/// ## Production notes
///
/// This reads the entire log into memory on every call. Fine for
/// pilot scale (10s of MB max); for SaaS we'll move to a streaming
/// JSONL response and per-tenant log shards.
async fn export_audit(
    State(state): State<AppState>,
    Query(query): Query<ExportQuery>,
    headers: HeaderMap,
) -> Result<Json<Vec<audit::AuditEntry>>, StatusCode> {
    // ─ Step 1: Pull and validate the auth headers. ─────────────────
    let signature = headers
        .get("X-Vyrox-Signature")
        .and_then(|v| v.to_str().ok())
        .ok_or(StatusCode::UNAUTHORIZED)?;

    let timestamp_str = headers
        .get("X-Vyrox-Timestamp")
        .and_then(|v| v.to_str().ok())
        .ok_or(StatusCode::UNAUTHORIZED)?;

    let timestamp: i64 = timestamp_str
        .trim()
        .parse()
        .map_err(|_| StatusCode::UNAUTHORIZED)?;

    // ─ Step 2: Replay window. ─────────────────────────────────────
    //
    // Same window as /execute. A stale `X-Vyrox-Timestamp` cannot be
    // used to repeatedly fetch a tenant's audit log forever.
    check_replay_window(timestamp).map_err(|_| StatusCode::UNAUTHORIZED)?;

    // ─ Step 3: HMAC verify on the canonical message. ──────────────
    //
    // The canonical message is `"<tenant_id>:<timestamp>"`. It binds
    // the request to (a) the tenant being queried, so an attacker
    // cannot swap the tenant_id query parameter without invalidating
    // the signature, and (b) the timestamp, so a replay outside the
    // window is impossible.
    let canonical = format!("{}:{}", query.tenant_id, timestamp);
    if let Err(err) = hmac::verify_signature(
        state.hmac_secret.as_bytes(),
        canonical.as_bytes(),
        signature,
    ) {
        warn!(error = %err, "audit export signature verification failed");
        return Err(StatusCode::UNAUTHORIZED);
    }

    // ─ Step 4: Actual export. ─────────────────────────────────────
    let entries = audit::read_audit_logs(&state.audit_log_path)
        .await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;

    let filtered: Vec<audit::AuditEntry> = entries
        .into_iter()
        .filter(|e| e.tenant_id == query.tenant_id)
        .collect();

    Ok(Json(filtered))
}

/// Parse a boolean-ish environment variable.
///
/// We accept the common spellings ("true"/"false"/"1"/"0"/"yes"/"no")
/// because operators write env files by hand and a strict parser leads
/// to silently-wrong DRY_RUN settings (which is exactly the failure mode
/// we cannot tolerate).
fn parse_bool_env(name: &str, default: bool) -> bool {
    match env::var(name) {
        Ok(value) => match value.trim().to_ascii_lowercase().as_str() {
            "1" | "true" | "yes" | "on" => true,
            "0" | "false" | "no" | "off" => false,
            other => {
                warn!(
                    var = name,
                    value = other,
                    default,
                    "unrecognized boolean env var; using default"
                );
                default
            }
        },
        Err(_) => default,
    }
}

/// Application entry point.
#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();

    // Required: secret used for HMAC verification. We refuse to start
    // without it — running with a default would silently disable auth.
    let hmac_secret = env::var("VYROX_HMAC_SECRET").expect("VYROX_HMAC_SECRET must be set");
    if hmac_secret.len() < 32 {
        warn!("VYROX_HMAC_SECRET is shorter than 32 bytes; consider rotating to a longer key");
    }

    let audit_log_path = env::var("AUDIT_LOG_PATH").unwrap_or_else(|_| "./audit.jsonl".to_string());

    // Safe-by-default: DRY_RUN is TRUE unless explicitly turned off.
    // Operators who want real execution must opt in.
    let dry_run = parse_bool_env("DRY_RUN", true);

    // Initialize the EDR client. See `edr.rs` for the configuration
    // contract — secrets are read from env there, not here.
    let edr = edr::EdrClient::from_env();

    // Seed the audit chain from the existing log file so a restart
    // continues the chain instead of branching from genesis. New
    // deployments with no log file fall through to the genesis hash.
    let audit_chain = audit::ChainState::from_file(&audit_log_path).await;

    let state = AppState {
        hmac_secret,
        audit_log_path,
        dry_run,
        nonces: nonce::NonceStore::new(),
        edr,
        audit_chain,
    };

    let app = Router::new()
        .route("/health", get(health))
        .route("/execute", post(execute))
        .route("/audit/export", get(export_audit))
        .with_state(state);

    // Bind address is configurable so the container/host can override
    // it. Default :3000 keeps backward compatibility with existing
    // deployment configs.
    let bind_addr = env::var("BIND_ADDR").unwrap_or_else(|_| "0.0.0.0:3000".to_string());

    // TLS is enabled when both BOTH cert and key paths are set. This is
    // an all-or-nothing toggle — partial config (one set, one missing)
    // is an operator error and we fail loudly so it's not mistaken for
    // a working TLS deploy.
    let tls_cert = env::var("TLS_CERT_PATH").ok();
    let tls_key = env::var("TLS_KEY_PATH").ok();

    match (tls_cert, tls_key) {
        (Some(cert), Some(key)) => {
            info!(addr = %bind_addr, tls = true, dry_run, "vyrox proxy starting (TLS)");
            let config = axum_server::tls_rustls::RustlsConfig::from_pem_file(&cert, &key)
                .await
                .expect("failed to load TLS cert/key — check TLS_CERT_PATH and TLS_KEY_PATH");
            axum_server::bind_rustls(bind_addr.parse().expect("invalid BIND_ADDR"), config)
                .serve(app.into_make_service())
                .await
                .expect("server should run");
        }
        (None, None) => {
            // Plain HTTP. Intended for deployment behind a TLS-terminating
            // reverse proxy (Cloudflare Tunnel, Caddy, nginx). NOT for
            // direct internet exposure.
            info!(addr = %bind_addr, tls = false, dry_run, "vyrox proxy starting (plain HTTP)");
            let listener = tokio::net::TcpListener::bind(&bind_addr)
                .await
                .expect("bind should work");
            axum::serve(listener, app).await.expect("server should run");
        }
        _ => panic!("TLS_CERT_PATH and TLS_KEY_PATH must both be set, or both unset"),
    }
}
